### ISSUE TITLE
다음 댓글 수집 오류

### ISSUE THREAD

**Issue by jky4098** [forkonlp/DNH4#16]
client_id <- httr::GET(turl)

  client_id <- httr::content(client_id)

  client_id <- rvest::html_nodes(client_id, ".alex-area")

  client_id <- rvest::html_attr(client_id, "data-client-id")

  tar <- paste0("https://comment.daum.net/auth/credential?client_id=", client_id)

  ad <- httr::add_headers(Referer = turl)
  auth <- httr::GET(tar, ad) 
  auth <- httr::content(auth)
 > ERROR

**Comment by mrchypark** [comment]
https://github.com/forkonlp/DNH4/commit/007dc2e7a21d0e5026bbdff78f775ed0170631c3

**Comment by mrchypark** [comment]
@all-contributors please add @jky4098 for bug
