### ISSUE TITLE
댓글 5000개 이상이면 에러가 납니다.

### ISSUE THREAD

**Issue by symbori** [forkonlp/DNH4#21]
2-3000개 까지는 문제 없이 되는데
5000을 넘어가게 되면 

> turl <- "http://v.media.daum.net/v/20200522093902880"
> commentA = DNH4::getAllComment(turl)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 100, 99

위와 같은 에러가 납니다. (다른 기사도 마찬가지였습니다.)

**Comment by mrchypark** [comment]
위 에러는 가져올 때 문제가 있는거 같네요. 살펴보겠습니다.

이슈 등록해주셔서 대단히 감사합니다.

**Comment by symbori** [comment]
변수명을 바꿔가며 여러번 시도하면, 몇 번의 에러 후 제대로 읽혀집니다. (일단은 그런 방식으로 필요한 자료들을 긁고 있는데, for 문은 못 돌리고 있네요....)  만개 넘는 댓글도 그런 식으로 하니 읽혀 지기는 합니다. 감사합니다.

**Comment by mrchypark** [comment]
https://github.com/forkonlp/DNH4/commit/16d43fe146d1478408c553486a9282efdf239238

문제 수정하였습니다. 확인해주세요 감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @symbori  for bug
