### ISSUE TITLE
getContent 함수 에러 발생

### ISSUE THREAD

**Issue by Yun-Hyunjun** [forkonlp/DNH4#24]
getContent 함수 실행 시, 아래와 같은 에러가 발생합니다.

Error in as.POSIXlt.character(datetime) : 

  문자열이 표준서식을 따르지 않습니다

getComment는 정상 작동합니다.

**Comment by mrchypark** [comment]
아래 커밋으로 문제 해결하였습니다. 이슈 재기해 주셔서 정말 감사드립니다.

깃헙 버전으로 새로 설치하시면 동작할 것 같구요. cran에는 빨리 반영하도록 하겠습니다. 감사합니다.

https://github.com/forkonlp/DNH4/commit/683ed5b231bf5bb3046bab3f6f1cfb2cb227a4dc
